import torch

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

AKTIVIERUNGSWORT_DATENBANK_PATH  = 'data/aktivierungswort.db'
AKTIVIERUNGSWORT_SAVE_MODEL = True
AKTIVIERUNGSWORT_RETRAIN_MODEL = False
AKTIVIERUNGSWORT_TRAINED_PATH = 'data/aktivierungswort.pth'
AKTIVIERUNGSWORT_TRAIN_BATCH_SIZE = 50
AKTIVIERUNGSWORT_VALIDATION_BATCH_SIZE = 50
AKTIVIERUNGSWORT_EPOCHS = 500
AKTIVIERUNGSWORT_HIDDEN_UNITS_1 = 32
AKTIVIERUNGSWORT_HIDDEN_UNITS_2 = 64

AUDIO_TMP_PATH = "data/audio_tmp.wav"

# AUTHENTIFIZIERUNG_AUTO_TRAINING = True

AUDIO_DB = 13
AUDIO_THRESHOLD = 500

AKTIVIERUNGSWORT_AUFNAHME_DAUER = 2
AKTIVIERUNGSWORT_AUFNAHME_PLOT = True
MAX_RECORDING_TIME = 8

TEXTKLASSIFIZIERUNG_SZENARIO_MIN_NOTEN = 0.9
TEXTKLASSIFIZIERUNG_ABSICHT_MIN_NOTEN = 0.9
AKTIVIERUNGSWORT_NOTEN = 0.9