import transformers
import torch

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

TEXTKLASSIFIZIERUNG_DATASET_PATH  = 'data/dataset/textklassifizierung.db'
TEXTKLASSIFIZIERUNG_TRAINED_PATH = 'data/result/textklassifizierung.pth'
TEXTKLASSIFIZIERUNG_META_PATH = 'data/textklassifizierung_meta.bin'

TEXTKLASSIFIZIERUNG_BASE_MODEL = 'dbmdz/bert-base-german-uncased'
TEXTKLASSIFIZIERUNG_TOKENIZER = transformers.BertTokenizer.from_pretrained(TEXTKLASSIFIZIERUNG_BASE_MODEL, do_lower_case = True)

TEXTKLASSIFIZIERUNG_MAX_LEN = 70
TEXTKLASSIFIZIERUNG_TRAIN_BATCH_SIZE = 50
TEXTKLASSIFIZIERUNG_VALIDATION_BATCH_SIZE = 50
TEXTKLASSIFIZIERUNG_EPOCHS = 100

TEXTKLASSIFIZIERUNG_SAVE_MODEL = True
TEXTKLASSIFIZIERUNG_RETRAIN_MODEL = True

AUTHENTIFIZIERUNG_SAVE_MODEL = True
AUTHENTIFIZIERUNG_RETRAIN_MODEL = True
AUTHENTIFIZIERUNG_DATASET_PATH  = 'data/dataset/authentifizierung.csv'
AUTHENTIFIZIERUNG_TRAINED_PATH = 'data/result/authentifizierung.pth'
AUTHENTIFIZIERUNG_META_PATH = 'data/authentifizierung_meta.bin'
AUTHENTIFIZIERUNG_TRAIN_BATCH_SIZE = 50
AUTHENTIFIZIERUNG_VALIDATION_BATCH_SIZE = 50
AUTHENTIFIZIERUNG_EPOCHS = 200
AUTHENTIFIZIERUNG_HIDDEN_UNITS_1 = 20
AUTHENTIFIZIERUNG_HIDDEN_UNITS_2 = 10
AUTHENTIFIZIERUNG_SAMPLE_RATE = 16000

RECORD_TMP_PATH = 'data/tmp/rec_tmp.wav'
SPEECH_TMP_PATH = 'data/tmp/speech_tmp.wav'

ABSICHT_ABFRAGEN = 1
ABSICHT_EINGEBEN = 2
ABSICHT_AENDERN = 3
ABSICHT_ENTFERNEN = 4

SZENARIO_WETTER = 1
SZENARIO_STUDIENORDNUNG = 2
SZENARIO_WIKIPEDIA = 3
SZENARIO_TODO_LIST = 4
SZENARIO_ZEIT = 5
SZENARIO_DATUM = 6

# ANMERKUNG_NONE = 1
ANMERKUNG_THEMA = 2
ANMERKUNG_ARTIKEL = 3
ANMERKUNG_ZEIT = 4
ANMERKUNG_DATUM = 5
ANMERKUNG_ORT = 6
ANMERKUNG_ZUSTAND = 7