import transformers
import torch

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

TEXTKLASSIFIZIERUNG_DATASET_PATH  = 'data/database/textklassifizierung.db'
TEXTKLASSIFIZIERUNG_TRAINED_PATH = 'data/result/textklassifizierung.pth'
TEXTKLASSIFIZIERUNG_META_PATH = 'data/textklassifizierung_meta.bin'

TEXTKLASSIFIZIERUNG_BASE_MODEL = 'dbmdz/bert-base-german-uncased'
TEXTKLASSIFIZIERUNG_TOKENIZER = transformers.BertTokenizer.from_pretrained(TEXTKLASSIFIZIERUNG_BASE_MODEL, do_lower_case = True)

TEXTKLASSIFIZIERUNG_MAX_LEN = 70
TEXTKLASSIFIZIERUNG_TRAIN_BATCH_SIZE = 50
TEXTKLASSIFIZIERUNG_VALIDATION_BATCH_SIZE = 50
TEXTKLASSIFIZIERUNG_EPOCHS = 100

TEXTKLASSIFIZIERUNG_SAVE_MODEL = True
TEXTKLASSIFIZIERUNG_RETRAIN_MODEL = True

AUTHENTIFIZIERUNG_SAVE_MODEL = True
AUTHENTIFIZIERUNG_RETRAIN_MODEL = False
AUTHENTIFIZIERUNG_TRAINED_PATH = 'data/result/authentifizierung.pth'
AUTHENTIFIZIERUNG_META_PATH = 'data/authentifizierung_meta.bin'
AUTHENTIFIZIERUNG_TRAIN_BATCH_SIZE = 50
AUTHENTIFIZIERUNG_VALIDATION_BATCH_SIZE = 50
AUTHENTIFIZIERUNG_EPOCHS = 50
AUTHENTIFIZIERUNG_HIDDEN_UNITS_1 = 20
AUTHENTIFIZIERUNG_HIDDEN_UNITS_2 = 10
AUTHENTIFIZIERUNG_SAMPLE_RATE = 26000
AUTHENTIFIZIERUNG_AUTO_TRAINING = True

USER_DATENBANK_PATH = 'data/database/benutzerprofil.db'

RECORD_TMP_PATH = 'data/tmp/rec_tmp.wav'

ABSICHT_ABFRAGEN = 1
ABSICHT_EINGEBEN = 2
ABSICHT_ENTFERNEN = 3

SZENARIO_WETTER = 1
SZENARIO_STUDIENORDNUNG = 2
SZENARIO_WIKIPEDIA = 3
SZENARIO_TODO_LIST = 4
SZENARIO_UHRZEIT = 5
SZENARIO_DATUM = 6

# ANMERKUNG_NONE = 1
ANMERKUNG_THEMA = 2
ANMERKUNG_AKTIVITAET = 3
ANMERKUNG_ZEIT = 4
ANMERKUNG_DATUM = 5
ANMERKUNG_ORT = 6

DEFAULT_ORT = "Dresden"

AUDIO_SPRACHE = "de-DE"
AUDIO_DB = 13
AUDIO_SIGNAL_LENGTH_SAVE = 2500
AUDIO_THRESHOLD = 0.006

ZEIT_STANDORT = "de_DE.UTF-8"

AUTHENTIFIZIERUNG_MIN_KONTO = 2
AUTHENTIFIZIERUNG_MIN_NOTEN = 0.95

TEXTKLASSIFIZIERUNG_SZENARIO_MIN_NOTEN = 0.8
TEXTKLASSIFIZIERUNG_ABSICHT_MIN_NOTEN = 0.8

ERROR_VARIABLE_DATUM = 1
ERROR_VARIABLE_ZEIT = 2
ERROR_VARIABLE_ORT = 3
ERROR_VARIABLE_AKTIVITAET = 4