import torch

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
USER_DATENBANK_PATH = 'data/benutzerdatenbank.db'
AUTHENTIFIZIERUNG_SAVE_MODEL = True
AUTHENTIFIZIERUNG_RETRAIN_MODEL = False
AUTHENTIFIZIERUNG_TRAINED_PATH = 'data/authentifizierung.pth'
AUTHENTIFIZIERUNG_META_PATH = 'data/authentifizierung_meta.bin'
AUTHENTIFIZIERUNG_TRAIN_BATCH_SIZE = 50
AUTHENTIFIZIERUNG_VALIDATION_BATCH_SIZE = 50
AUTHENTIFIZIERUNG_EPOCHS = 150
AUTHENTIFIZIERUNG_HIDDEN_UNITS_1 = 20
AUTHENTIFIZIERUNG_HIDDEN_UNITS_2 = 10
AUTHENTIFIZIERUNG_PLOT_CONFUSION_MATRIX = False

# AUTHENTIFIZIERUNG_MIN_KONTO = 3
AUTHENTIFIZIERUNG_MIN_NOTEN = 0 # 0.95

# AUDIO_SIGNAL_LENGTH_SAVE = 8000
AUDIO_SAVE_SPLIT = 2