import torch
import argparse

parser = argparse.ArgumentParser(description="Shared-Data-Service (Server)")
parser.add_argument('--ip', type=str, required=True, help='Shared-Data-Service IP')
parser.add_argument('--port', type=int, required=True, help='Shared-Data-Service Port')
args = parser.parse_args()
#############################################################################
SHARED_DATA_SERVICE_IP = args.ip
SHARED_DATA_SERVICE_PORT = args.port

TEXTKLASSIFIZIERUNG_SERVICE_IP = "localhost"
TEXTKLASSIFIZIERUNG_SERVICE_PORT = 8001

KONTOVERWALTUNG_SERVICE_IP = "localhost"
KONTOVERWALTUNG_SERVICE_PORT = 8002

SPEECH_TO_TEXT_SERVICE_IP = "localhost"
SPEECH_TO_TEXT_SERVICE_PORT = 8003

TEXT_TO_SPEECH_SERVICE_IP = "localhost"
TEXT_TO_SPEECH_SERVICE_PORT = 8004

DATUM_INTENT_SERVICE_IP = "localhost"
DATUM_INTENT_SERVICE_PORT = 8005

UHRZEIT_INTENT_SERVICE_IP = "localhost"
UHRZEIT_INTENT_SERVICE_PORT = 8006

WETTER_INTENT_SERVICE_IP = "localhost"
WETTER_INTENT_SERVICE_PORT = 8007

WIKIPEDIA_INTENT_SERVICE_IP = "localhost"
WIKIPEDIA_INTENT_SERVICE_PORT = 8008

STUDIENORDNUNG_INTENT_SERVICE_IP = "localhost"
STUDIENORDNUNG_INTENT_SERVICE_PORT = 8009

TODOLIST_INTENT_SERVICE_IP = "localhost"
TODOLIST_INTENT_SERVICE_PORT = 8010

SEARCH_ENGINE_INTENT_SERVICE_IP = "localhost"
SEARCH_ENGINE_INTENT_SERVICE_PORT = 8011

YOUTUBE_INTENT_SERVICE_IP = "localhost"
YOUTUBE_INTENT_SERVICE_PORT = 8012
#############################################################################
DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

ZEIT_STANDORT = "de_DE.UTF-8"
AUDIO_SAMPLE_RATE = 16000

ABSICHT_ABFRAGEN = 1
ABSICHT_EINGEBEN = 2
ABSICHT_ENTFERNEN = 3
ABSICHT_ZURUECKGEHEN = 4
ABSICHT_WEITERGEHEN = 5
ABSICHT_WIEDERHOLEN = 6
ABSICHT_ABBRECHEN = 7

SZENARIO_WETTER = 1
SZENARIO_STUDIENORDNUNG = 2
SZENARIO_WIKIPEDIA = 3
SZENARIO_TODO_LIST = 4
SZENARIO_UHRZEIT = 5
SZENARIO_DATUM = 6
SZENARIO_SYSTEM = 7
SZENARIO_YOUTUBE = 8
SZENARIO_SEARCH_ENGINE = 9

# ANMERKUNG_NONE = 1
ANMERKUNG_THEMA = 2
ANMERKUNG_AKTIVITAET = 3
ANMERKUNG_ZEIT = 4
ANMERKUNG_DATUM = 5
ANMERKUNG_ORT = 6

ERROR_VARIABLE_DATUM = 1
ERROR_VARIABLE_ZEIT = 2
ERROR_VARIABLE_ORT = 3
ERROR_VARIABLE_AKTIVITAET = 4
ERROR_VARIABLE_THEMA = 5
#############################################################################