== Assistenten aufrufen
Nun kann der Assistent nach Belieben aufgerufen werden

Standardaktivierungswort: `Tim`

. Benutzer: Hey Tim
. Assistent: Ja
. Benutzer: `Befehl eingeben`

== Start der Anwendung
=== Start des Servers
In das Server Verzeichnis wechseln
[source,cmd]
----
cd assistant_ai\server
----
Die Virtuelle Umgebung existiert bereits und muss nun erneut aktiviert werden.

Virtuelle Umgebung aktivieren
[source,cmd]
----
assistant_ai_server\Scripts\activate
----
In das Main Server Verzeichnis wechseln.

[source,cmd]
----
cd .\main_server
----

Die 13 Microservices in der richtigen Reihenfolge starten

[source,cmd]
----
python main.py ^
  --main_server_ip localhost --main_server_port 8000 ^
  --kontoverwaltung_ip localhost --kontoverwaltung_port 8001 ^
  --textklassifizierung_ip localhost --textklassifizierung_port 8002 ^
  --speech_to_text_ip localhost --speech_to_text_port 8003 ^
  --text_to_speech_ip localhost --text_to_speech_port 8004 ^
  --datum_intent_ip localhost --datum_intent_port 8005 ^
  --uhrzeit_intent_ip localhost --uhrzeit_intent_port 8006 ^
  --wetter_intent_ip localhost --wetter_intent_port 8007 ^
  --wikipedia_intent_ip localhost --wikipedia_intent_port 8008 ^
  --studienordnung_intent_ip localhost --studienordnung_intent_port 8009 ^
  --todolist_intent_ip localhost --todolist_intent_port 8010 ^
  --search_engine_intent_ip localhost --search_engine_intent_port 8011 ^
  --youtube_intent_ip localhost --youtube_intent_port 8012
----

=== Start des Clients
In das Client Verzeichnis wechseln
[source,cmd]
----
cd assistant_ai\client
----
Die Virtuelle Umgebung existiert bereits und muss nun erneut aktiviert werden.

Virtuelle Umgebung aktivieren
[source,cmd]
----
assistant_ai_client\Scripts\activate
----

Jetzt muss die engine.py Datei aufgerufen werden.
[source,cmd]
----
python engine.py
----
==== Hinweis:
   - HTW DRESDEN SERVER
      - Server-IP: `141.56.137.185`
      - Server-Port: `8000`
   - Eigener Server 
      - Server-IP: `localhost`
      - Server-Port: `8000`

=== Assistenten aufrufen
Nun kann der Assistent nach belieben aufgerufen werden

Standardaktivierungswort: `Tim`

1. Benutzer: Hey Tim
2. Assistent: Ja
3. Benutzer: `Befehl eingeben`

Hinweis:
Der Sprachassistent kann derzeit nur eine Anfrage beantworten. Für weitere Anfragen muss erneut das Aktivierungswort gesagt werden.